apiVersion: apps/v1
kind: Deployment
metadata:
  name: test
  namespace: jenkins
  labels:
    app: test
spec:
  replicas: 1
  selector:
    matchLabels:
      app: test
  template:
    metadata:
      labels:
        app: test
    spec:
      containers:
      - name: test-container  # Tên của container
        image: dxcuong206/test:04  # Hình ảnh container
        ports:
        - containerPort: 80
---
apiVersion: v1
kind: Service
metadata:
  name: test
  namespace: jenkins
  labels:
    app: test
spec:
  type: NodePort
  ports:
  - protocol: TCP
    port: 80
    targetPort: 80
    nodePort: 30003
  selector:
    app: test
