apiVersion: v1
kind: Pod
metadata:
  name: jnlp
  namespace: jenkins
spec:
  containers:
  - name: jnlp
    image: dxcuong206/test:03
    imagePullPolicy: IfNotPresent
    env:
    - name: http_proxy
      value: "http://10.26.2.55:8080"
    - name: https_proxy
      value: "http://10.26.2.55:8080"
    - name: no_proxy
      value: "localhost,10.0.0.0/8,172.16.0.0/12,192.168.0.0/16,169.254.0.0/16,127.0.0.0/8"
    volumeMounts:
    - name: kubectl-binary
      mountPath: /usr/local/bin/kubectl
      readOnly: true
  volumes:
    - name: kubectl-binary
      hostPath:
        path: /usr/bin/kubectl
  imagePullSecrets:
  - name: registry
